import Header from '@/components/Header'
import React from 'react'

export const metadata = {
  title: 'Our Approach',
  description: 'Generated by create next app',
  icons:{
    icon: "/favicon.ico"
  }
}

type Props = {}

const page = (props: Props) => {
  return (
    <div className='min-h-[100vh]'>
      <Header 
      title='Our Approach'
      description='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
      image='contact-header.jpg'
      />

      <div className='flex h-96'>

        <div className='bg-black w-3/5  items-start pl-96 pt-40 pb-16' >


          <h1 className=' text-4xl text-teal-300'> The best people </h1>
          <h1 className=' text-4xl text-white'> are on the job </h1>




        </div>

        <div className=' bg-black w-2/5  items-start flex' >


          <div className=' pt-36'>

            <img 
              src="/images/__Turntabl_Digital_Hand_5.png"
              alt='logo'
              width={200}
              height={200}
              className='object-contain'
            />

          </div>


        </div>
      </div>
      


      <div className='flex'>

        <div className=' background_green w-1/2  items-start pl-80 pt-16 pb-16' >


          <h1 className=' text-4xl'> Changing the world starts with collaboration. </h1>
          <p className='pr-10'>Collaboration starts with a shared goal. That means complementary knowledge and mutual understanding. That’s how we work with you.

You bring the goals, the aim of making the world better, and an open approach to getting results. We bring the talent, the solutions-oriented approach, and the final results. And Ghana’s capacity for top-tier software consultancy services becomes more and more sustainable. That’s why we work with you.

We supply Ghana’s most skilled engineers – veterans of our education partnership with Global Code. They bring years of experience in graduate training for Fortune 500 companies to solve your problems, maximise your efficiency and surpass your goals. By collaborating with you, they see how the world works and the good your organisation does.

Together, we get the job done. Together, we’ll create a finer world.
</p>
          

          


        </div>

        <div className=' background_green w-1/2  items-start flex' >


          <div className='pt-20'>

          <img 
            src="/images/why-turntabl.png"
            alt='logo'
            width={400}
            height={400}
            className='object-contain'
          />

          </div>

          


        </div>
      </div>
      
      </div>
  )
}

export default page