import Header from "@/components/Header";
import React, { useRef } from "react";
import ContactForm from "./ContactForm";
import Link from "next/link";

export const metadata = {
  title: "Contact us",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

type Props = {};

const page = (props: Props) => {
  return (
    <div className="min-h-[100vh]">
      <Header
        title="Contact us"
        description={
          "Ready to reinvent the status quo?\nContact us now for an obligation free chat!"
        }
        image="contact-header.jpg"
      />
      <div className="flex items-center justify-center w-full bg-cover">
        <ContactForm />
      </div>
      <div className="bg-black">
        <div></div>
        <div className=" text-center p-9">
          <h6 className=" text-4xl text-white"> Visit turntabl at</h6>
        </div>
        <div className="flex justify-center">
          <Link href={"https://goo.gl/maps/PaWe9YvtMebZMVUWA"}>
            <h1 className=" text-4xl text-teal-300"> Sonnidom House </h1>{" "}
          </Link>
          <h1> ' '</h1>
          <h6 className=" text-4xl text-white"> or</h6>
          <h1> ' '</h1>
          <Link href="https://goo.gl/maps/8j6uhcUUVaTcCT8Z7">
            <h1 className=" text-4xl text-teal-300"> Advantage Place</h1>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default page;
