import Header from '@/components/Header'
import React from 'react'

export const metadata = {
  title: 'Contact us',
  description: 'Generated by create next app',
  icons:{
    icon: "/favicon.ico"
  }
}

type Props = {}

const page = (props: Props) => {
  return (
    <div className='min-h-[100vh]'>

      <Header 
        title='Contact us'
        description='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
        image='contact-header.jpg'
      />

      <div className='flex h-96'>

        <div className='bg-black w-3/5  items-start pl-96 pt-40 pb-16' >


          <h1 className=' text-4xl text-teal-300'> Ready to reinvent </h1>
          <h1 className=' text-4xl text-white'> the status quo? </h1>

        </div>

        <div className=' bg-black w-2/5  items-start flex' >


          <div className=' pt-36'>

            <img 
              src="/images/__Turntabl_Digital_Hand_5.png"
              alt='logo'
              width={200}
              height={200}
              className='object-contain'
            />

          </div>


        </div>
      </div>
      

      <div className=' h-10'>form here</div>

      <div className=' bg-black' >

        <div className=' text-center p-9'>

            
          <h6 className=' text-4xl text-white'> Visit turntabl :)</h6>
          <h6 className=' text-4xl text-teal-400'> at </h6>              
            

        </div>


      </div>

















      <div className='flex'>

        <div className=' bg-black w-1/3  items-start text-center pt-16 pb-16' >


          <h1 className=' text-4xl text-teal-300'> Sonnidom </h1>
          <h1 className=' text-4xl text-white'> House</h1>

        </div>

        <div className=' bg-black w-1/3  items-start text-center pt-16 pb-16' >


          <h1 className=' text-4xl text-white'> Or?</h1>

        </div>

        <div className=' bg-black w-1/3  items-start text-center pt-16 pb-16' >


          <h1 className=' text-4xl text-teal-300'> Advantage </h1>
          <h1 className=' text-4xl text-white'> Place</h1>

        </div>

        
      </div>














      <div className='flex'>

        <div className=' bg-black w-1/2  items-start pr-1' >

        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3970.552258059788!2d-0.24308760321041675!3d5.632905500000006!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xfdf999c2b31624f%3A0xa8df567cb2e57a26!2sSonnidom%20fuel%20station%20-%20Achimota%2FMile%207!5e0!3m2!1sen!2sgh!4v1688914195560!5m2!1sen!2sgh" width="100%" height="450"  loading="lazy" ></iframe>


          

          


        </div>

        <div className=' bg-black w-1/2  items-start flex pl-1' >


        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3971.0402161048764!2d-0.2036413251002952!3d5.5610579944194045!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xfdf909ee3aceab1%3A0x4010a55a4675b5cb!2sAdvantage%20Place!5e0!3m2!1sen!2sgh!4v1688913964879!5m2!1sen!2sgh" width="100%" height="450"  loading="lazy" ></iframe>

          


        </div>
      </div>








        

        
    </div>

  )
}

export default page