import Header from '@/components/Header'
import React from 'react'

export const metadata = {
  title: 'About us',
  description: 'Generated by create next app',
  icons:{
    icon: "/favicon.ico"
  }
}

type Props = {}
import mypic from '../../../public/images/contact-header.jpg'

const page = (props: Props) => {
  return (
    <div className='min-h-[100vh]'>
      <Header 
      title='About Us'
      description='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
      image='contact-header.jpg'
      />

      <div className='flex'>

        <div className='bg-black w-3/5  items-start pl-96 pt-16 pb-16' >


          <h1 className=' text-4xl text-teal-300'> We Provide Innovative </h1>
          <h1 className=' text-4xl text-white'> Software Engineering</h1>
          <h1 className=' text-4xl text-white'> Solutions To Businesses </h1>
          <h1 className=' text-4xl text-white'> All Over The World. </h1>

  


        </div>

        <div className=' bg-black w-2/5  items-start flex' >


          <div className=' pt-5'>

            <img 
              src="/images/__Turntabl_Digital_Hand_5.png"
              alt='logo'
              width={200}
              height={200}
              className='object-contain'
            />

          </div>

        
        </div>
      </div>

      <div className='flex'>

        <div className=' bg-white w-1/2  items-start pl-72 pt-16 pb-16' >


          <h1 className=' text-4xl'> We are Ghana's </h1>
          <h1 className=' text-4xl'> Technology</h1>
          <h1 className=' text-4xl'> Leaders </h1>

          <p>We provide your company with the best engineering</p>
          <p>services. Here, the most talented and creative experts</p>
          <p>work with the world’s leading organizations on initiatives</p>
          <p>that promote social change. We thrive on advancing</p>
          <p>global collaboration, developing software, and overcoming</p>
          <p>obstacles.</p>

  


        </div>

        <div className=' bg-white w-1/2  items-start flex' >


          <div className=' pt-5'>

            <img 
              src="/images/BOwusuNyantekyi_turntabl_pre-edits_20220602_022_V2.jpg"
              alt='logo'
              width={500}
              height={500}
              className='object-contain'
            />

          </div>

        
        </div>
      </div>


      <div className='flex'>

        <div className=' bg-black w-1/2  items-start pl-96 pt-16 pb-16' >


          <h1 className=' text-4xl text-white'> Why </h1>
          <h1 className=' text-4xl text-teal-300'> Ghana?</h1>

          


        </div>

        <div className=' bg-black w-1/2  items-start flex' >


          <div className=' pt-16 pb-10'>

            <p className=' text-white'>With our partner, Global Code, turntabl Labs Produces</p>
            <pre> </pre>
            <ul className="list-disc pl-4">
              <li className='text-teal-100'>Highly-skilled professionals led by industry veterans</li>
              <li className='text-teal-100' >Fortune 500-level engineers</li>
              <li className='text-teal-100' >Diverse and affordable technology services</li>
            </ul>
            <pre> </pre>
            <p className=' text-white' >Through its national values of democracy, hard work and</p>
            <p className=' text-white' >online freedom, Ghana’s tech revolution has shattered</p>
            <p className=' text-white' >is your future: today. Learn more about our unique</p>
            <p className=' text-white' >approach here...</p>
            <pre> </pre>
            <p className=' text-white' >Learn more about what makes us so special here.</p>

          </div>

          


        </div>
      </div>


      <div className=' bg-black flex justify-center pt-10'>

        <img 
            src="/images/why-turntabl.png"
            alt='logo'
            
            className='object-contain'
        />
        
      </div>

      <div className='flex'>

        <div className=' bg-white w-1/2  items-start pl-96 pt-16 pb-16' >


          <h1 className=' text-4xl'> Our </h1>
          <h1 className=' text-4xl'> People</h1>

          


        </div>

        <div className=' bg-white w-1/2  items-start flex' >


         

          


        </div>
      </div>
      

      
    </div>
  )
}

export default page