import Banner from '@/components/Banner'
import Blog from '@/components/Blog'
import Hero from '@/components/Hero'
import Services from '@/components/Services'
import Values from '@/components/Values'

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
  icons: {
    icon: "/favicon.ico"
  }
}

export default function Home() {
  return (

    <main className="bg-gray-100 flex min-h-screen flex-col  justify-between">
      <Hero />
      <Values />
      <Services />
      <Banner />
      <Blog />
    </main>
  )
}
