import Hero from '@/components/Hero'

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
  icons:{
    icon: "/favicon.ico"
  }
}

export default function Home() {
  return (
    <main className="bg-slate-100 flex min-h-screen flex-col  justify-between">
      <Hero/>

      <div>

        <div className=' bg-black' >

          <div className=' text-center p-9'>

            <div>
              <h6 className=' text-4xl text-white'> Akwaaba :)</h6>
              <h6 className=' text-4xl text-teal-400'> We are </h6>
              <h6 className=' text-4xl text-teal-400'> Turntabl </h6>
              <p className='text-teal-400'>From our offices in Ghana and London, we build best-in-class software for the world's biggest enterprises</p>

              <p className='text-white'>We’re an employee-owned consultancy establishing Ghana as a premier tech hub. </p>
              <p className='text-white'>Our team of highly talented, globally-trained software engineers are dedicated to your business’s success.</p>

              <p className='text-white'>Let’s disrupt the status quo together</p>

              <p className='text-teal-400'>Here at turntabl we pride ourselves in our...</p>

              
            </div>

          </div>


        </div>

        <div className=' bg-gray-500   items-start flex p-9' >

          <div className = "w-11/12 ml-20 mr-20">

            {/* <img 
            src="/images/TT Logo.png"
            alt='logo'
            width={30}
            height={30}
            className='object-contain'
            /> */}



            <h1 className=' text-2xl pb-3 text-white'>
              Client satisfaction
            </h1>
            <p> We understand that our success is intrinsically linked to the success of our clients. Therefore, we strive to exceed their expectations and deliver exceptional service at every stage of our engagement. </p>


          </div>


          <div className = "w-11/12 ml-20 mr-20">

            {/* <img 
            src="/images/TT Logo.png"
            alt='logo'
            width={30}
            height={30}
            className='object-contain'
            /> */}



            <h1 className=' text-2xl pb-11 text-white'>
              Ingenuity
            </h1>
            <p> Turntabl is always looking to improve and with our emphasis on continous learning we ensure that we're at the forefront of most technologies </p>

            
          </div>

          <div className = "w-11/12 ml-20 mr-20">

            <h1 className=' text-2xl pb-3 text-white'>
              Technical Expertise
            </h1>
            <p> Our company takes great pride in our extensive technical expertise, which serves as the foundation of our success. We are a team of highly skilled and experienced professionals who are passionate about staying at the forefront of the ever-evolving technology landscape. </p>

            
          </div>

          <div className = "w-11/12 ml-20 mr-20">

            <h1 className=' text-2xl pb-11 text-white'>
              Security
            </h1>
            <p> Security is a paramount concern, and we prioritize it in every aspect of our work. We understand the critical importance of safeguarding sensitive data, protecting privacy, and mitigating potential risks for our clients.</p>

            
          </div>

        </div>
      </div>
      







      <div className=' background_purple'> 
      
        <div className=' text-center p-9'>
          <h1 className=' text-4xl'> What we <span className=' text_brown'>can</span> do for you </h1>

          <p> Whatever software your business requires, we are able to </p>
          <p> design and develop a bespoke solution tailored </p>
          <p> specifically to your needs. </p>
        </div>


      </div>

      <div className=' background_purple'>

        <div className=' flex items-baseline justify-center w-10/11 m-auto '>

          <div className='px-16'>

           <p >Innovative strategy</p>
           <pre> </pre>
           <p className='text_gray' >Digital Product Strategy</p>
           <pre> </pre>
           <p>Technology Architecture</p>
          

          </div>

          <div className='px-16'>

            <p>Information Architecture</p>
            <pre> </pre>
            <p className='text_gray' >Digital Product Design</p>
            <pre> </pre>
            <p>UX Research & Design</p>
            <pre> </pre>
            <p className='text_gray' >Web App Development</p>

          </div>

          <div className='px-16'>

            <p>Magento Development</p>
            <pre> </pre>
            <p className='text_gray' >Wordpress Development</p>
            <pre> </pre>
            <p>Mobile App Development</p>
          
          </div>

        </div>

      </div>

      <div className=' background_purple'> 
      
        <div className='text-center p-9'>
        <h1 className=' text-2xl'> Contact us now for an obligation-free conversation </h1>

          <p className='text_gray' > about how we can help your business. </p>

          <a href = '/contact-us'className=' button mt-3'> Let's chat </a>
          
        </div>


      </div>






      <div className='flex'>

        <div className=' background_green w-1/2  items-start pl-96 pt-16 pb-16' >


          <h1 className=' text-5xl'> Why </h1>
          <h1 className=' text-5xl text_brown'> turntable?</h1>

          


        </div>

        <div className=' background_green w-1/2  items-start flex' >


          <div className=' pt-16'>

            <p>From Ghana, we connect you to a world of solutions.</p>
            <pre> </pre>
            <p>When you work with us, not only are you served by some of the</p>
            <p>world's best software engineers, you're also enhancing Ghana's</p>
            <p>professional development. The gateway to the world now lies in West</p>
            <p>Africa.</p>
            <pre> </pre>
            <p>Learn more about what makes us so special here.</p>

          </div>

          


        </div>
      </div>


      <div className=' background_green flex justify-center pt-10'>

        <img 
            src="/images/why-turntabl.png"
            alt='logo'
            
            className='object-contain'
        />
        
      </div>












      <div className=' bg-black'> 
      
        <div className='text-center p-9'>
          <h1 className='text-4xl text-white'> Do not just take our word for it</h1>

          <p className=' text_brown'> Hear from some of our wonderful clients </p>
        </div>


      </div>

      <div className=' bg-black flex justify-evenly'> 

        <img 
            src="/images/fidelity.png"
            alt='logo'
            width={90}
            height={90}
            className='object-contain'
        />

        <img 
            src="/images/finos.png"
            alt='logo'
            width={90}
            height={90}
            className='object-contain'
        />

        <img 
            src="/images/ms.png"
            alt='logo'
            width={90}
            height={90}
            className='object-contain'
        />

        <img 
            src="/images/ms.png"
            alt='logo'
            width={90}
            height={90}
            className='object-contain'
        />

      </div>

      <div className='flex'>

        <div className=' bg-black w-1/2  items-start pl-52 pt-16 pb-16' >


          <h1 className='text-2xl text-white'> On why turntabl is your one stop shop</h1>
          <h1 className='text-2xl text_brown'>  for all your needs</h1>
          <pre> </pre>
          <p>Real stories from real clients</p>


        </div>

        <div className=' bg-black w-1/2  items-start flex pt-16' >


          <div className = "">

            <p className='text-white'> "The best agency I have worked with" </p>

            <div className=' flex items-center pt-5'>

              <img 
              src="/images/whiteuser.png"
              alt='logo'
              width={25}
              height={25}
              className='object-contain'
              />

              <div className='pt-3 pl-2'>
                <h1 className='text-white'>Victoria Asamoah</h1>
                <p className='text-xs text-white'> CEO of Asamoah Enteprises</p>

                

              </div>

              

             

            </div>



            <div className='pt-6 pl-7'>
              <a className='text-white'> More reviews... </a>
            </div>

          </div>


        </div>
      </div>

      


      

      <div className=' bg-white'> 
      
        <div className='text-center p-9'>
          <h1 className=' text-4xl'> Take a Look at our <span className=' text_brown'>blog</span> </h1>

          <p className='text_gray' > Get the latest from turntabl </p>
          <p className='text_gray' > Where we delve into the fascinating world of software development, </p>
          <p className='text_gray' > exploring the latest trends, best practices, and insights that shape the industry.  </p>
        </div>


      </div>

      <div className=' bg-white'>

        {/* <div className=' flex items-baseline justify-evenly w-10/11 m-auto'> */}
        <div className=' flex justify-evenly w-10/11 m-auto'>

          <div className=' w-11/12 ml-20 mr-20'>


            <img 
              src="/images/why-turntabl.png"
              alt='logo'
              width={300}
              height={300}
              className='object-contain'
            />

            <p className=' text-xs py-3'> 26 June, 2023</p>

            <h1>
                <b>Is environmental sustainability pretentious or boring</b>
            </h1>


            <p className=' text-xs py-3'> Let's find out </p>

          </div>

          <div className=' w-11/12 ml-20 mr-20'>

            <img 
              src="/images/why-turntabl.png"
              alt='logo'
              width={300}
              height={300}
              className='object-contain'
            />

            <p className=' text-xs py-3'> 2 May, 2023</p>

            <h1>
                <b>IoT Explained: Why The Internet of Things is Our Future</b>
            </h1>


            <p className=' text-xs py-3'> Wanna know more </p>
          

          </div>

          <div className=' w-11/12 ml-20 mr-20'>

            <img 
              src="/images/why-turntabl.png"
              alt='logo'
              width={300}
              height={300}
              className='object-contain'
            />

            <p className=' text-xs py-3'> 3 April, 2023</p>

            <h1>
                <b>My turntabl Journey</b>
            </h1>


            <p className=' text-xs py-3'> Learn what it takes to be a turntablr </p>
          

          </div>

          <div className=' w-11/12 ml-1 mr-20 pt-12'>

            <img 
              src="/images/right.png"
              alt='logo'
              width={50}
              height={50}
              className='object-contain'
            />

            <p className=' text-xs py-3'> Get more from turntabl </p>

            

          </div>

        </div>

      </div>

    </main>
  )
}
