import Header from '@/components/Header'
import React from 'react'

export const metadata = {
  title: 'Our Services',
  description: 'Generated by create next app',
  icons:{
    icon: "/favicon.ico"
  }
}

type Props = {}

const page = (props: Props) => {
  return (
    <div className='min-h-[100vh]' >
      <Header 
      title='Our Services'
      description=' Leading global talent to your software solutions'
      image='contact-header.jpg'
      />


      




      
      


      <div className='flex'>

        <div className='  w-1/2  items-start pl-80 pt-16 pb-16 pr-32' >


          <h1 className=' text-4xl'> Innovation Strategy </h1>
          <p>At <span className=' text_purple'>turntabl</span>, we are committed to fostering a culture of innovation that drives our success in a rapidly evolving market. Our innovation strategy is centered around anticipating and meeting the changing needs of our customers, while continuously exploring new opportunities for growth and differentiation..</p>


          


        </div>

        <div className='  w-1/2  items-start flex pt-16 pb-16' >


        <div className='wrapper'>

<div className=' parent'>

<div className=' child'>

  <img 
    src="/images/why-turntabl.png"
    alt='logo'
    width={400}
    height={400}
    className='object-contain'
  />
</div>


</div>

</div>  

          


        </div>
      </div>

      <div className='flex'>

        <div className='  w-1/2  items-start flex pt-16 pb-16' >


        <div className='wrapper'>

<div className=' parent'>

<div className=' child pl-80'>

  <img 
    src="/images/why-turntabl.png"
    alt='logo'
    width={400}
    height={400}
    className='object-contain'
  />
</div>


</div>

</div>  

        </div>


        <div className='  w-1/2  items-start  pt-16 pb-16 pr-80' >


          <h1 className=' text-4xl'> Digital Product Strategy </h1>
          <p>Our digital product strategy revolves around three key pillars: customer-centricity, innovation, and seamless integration. By deeply understanding our customers' needs and pain points, we develop digital products that not only meet their expectations but exceed them. We invest heavily in user research, employing data-driven insights to inform our product development decisions and ensure our solutions align with user preferences and behaviors.</p>
          

          


        </div>

      </div>

      <div className='flex'>

        <div className='  w-1/2  items-start pl-80 pt-16 pb-16 pr-32' >


          <h1 className=' text-4xl'> Technology Architecture</h1>
          <p>Scalability, flexibility, and interoperability builds our technology architecture. We leverage cloud computing infrastructure to ensure scalability and elasticity, enabling us to rapidly scale our systems as demand grows while optimizing costs. This allows us to seamlessly handle increased data volumes, user traffic, and complex computational requirements.</p>


          


        </div>

        <div className='  w-1/2  items-start flex pt-16 pb-16' >


        <div className='wrapper'>

<div className=' parent'>

<div className=' child '>

  <img 
    src="/images/why-turntabl.png"
    alt='logo'
    width={400}
    height={400}
    className='object-contain'
  />
</div>


</div>

</div>  

          


        </div>
      </div>

      <div className='flex'>

        <div className=' bg_purple w-1/2  items-start flex pt-16 pb-16' >


          <div className='wrapper'>

            <div className=' parent'>

            <div className=' child pl-80'>

              <img 
                src="/images/why-turntabl.png"
                alt='logo'
                width={400}
                height={400}
                className='object-contain'
              />
            </div>
            

            </div>

            </div>  

        </div>


        <div className='bg_purple  w-1/2  items-start  pt-16 pb-16 pr-80' >


          <h1 className=' text-4xl'>  Information Architecture </h1>
          <p>Our information architecture is designed with a focus on data integrity, accessibility, and usability. We adhere to industry best practices and standards to ensure the accuracy, consistency, and reliability of our data. By establishing robust data governance frameworks, we enforce data quality controls, establish data ownership, and define clear data management processes.</p>
          

          


        </div>

      </div>

      <div className='flex'>

        <div className='bg_purple  w-1/2  items-start pl-80 pt-16 pb-16 pr-32' >


          <h1 className=' text-4xl'> Digital Product Design</h1>
          <p>We begin our digital product design process with deep user research and understanding. We conduct user interviews, usability testing, and gather feedback to gain insights into the needs, preferences, and pain points of our target audience. By empathizing with our users, we ensure that our designs address their real-world challenges and deliver meaningful value.</p>


          


        </div>

        <div className='bg_purple  w-1/2  items-start flex pt-16 pb-16' >


        <div className='wrapper'>

<div className=' parent'>

<div className=' child'>

  <img 
    src="/images/why-turntabl.png"
    alt='logo'
    width={400}
    height={400}
    className='object-contain'
  />
</div>


</div>

</div>  

          


        </div>
      </div>

      <div className='flex'>

        <div className='bg_purple  w-1/2  items-start flex pt-16 pb-16' >


        <div className='wrapper'>

<div className=' parent'>

<div className=' child pl-80'>

  <img 
    src="/images/why-turntabl.png"
    alt='logo'
    width={400}
    height={400}
    className='object-contain'
  />
</div>


</div>

</div>  

        </div>


        <div className='bg_purple  w-1/2  items-start  pt-16 pb-16 pr-80' >


          <h1 className=' text-4xl'> UX Research & Design </h1>
          <p>We cooperate with you throughout the UX research and design process to gain a deep understanding of our target audience. We conduct comprehensive user research to gain insights into their behaviors, motivations, and pain points. Through methods such as user interviews, surveys, and observation, we uncover valuable user perspectives that guide our design decisions.</p>
          

          


        </div>

      </div>

      <div className='flex'>

        <div className='bg_green text-black  w-1/2  items-start pl-80 pt-16 pb-16 pr-32' >


          <h1 className=' text-4xl'> Magento Development </h1>
          <p>Our Magento development team comprises experienced professionals who specialize in leveraging the platform's extensive features and customization options. We work closely with our clients to understand their unique business requirements, enabling us to design and develop Magento-based solutions that align with their goals and provide a seamless user experience.</p>


          


        </div>

        <div className='bg_green text-black  w-1/2  items-start flex pt-16 pb-16' >


        <div className='wrapper'>

<div className=' parent'>

<div className=' child'>

  <img 
    src="/images/why-turntabl.png"
    alt='logo'
    width={400}
    height={400}
    className='object-contain'
  />
</div>


</div>

</div>  

          


        </div>
      </div>

      <div className='flex'>

        <div className='bg_green text-black  w-1/2  items-start flex pt-16 pb-16' >


        <div className='wrapper'>

<div className=' parent'>

<div className=' child pl-80'>

  <img 
    src="/images/why-turntabl.png"
    alt='logo'
    width={400}
    height={400}
    className='object-contain'
  />
</div>


</div>

</div>  

        </div>


        <div className='bg_green text-black  w-1/2  items-start  pt-16 pb-16 pr-80' >


          <h1 className=' text-4xl'> Wordpress Development </h1>
          <p> At <span className=' text_purple'>turntabl</span>, we have extensively trained our team of experienced WordPress developers and skilled in leveraging the extensive features and flexibility of the platform. We work closely with our clients to understand their specific goals, branding, and functionality requirements. This collaborative approach allows us to design and develop WordPress-based websites that not only reflect their vision but also provide an intuitive and seamless user experience.</p>
          

          


        </div>

      </div>

      <div className='flex'>

        <div className='bg-black text-white  w-1/2  items-start pl-80 pt-16 pb-16 pr-32' >


          <h1 className=' text-4xl text_green'> Mobile App Development </h1>
          <p>Our team of skilled mobile app developers possesses extensive expertise in developing apps for various platforms, including iOS and Android. We work closely with our clients to understand their unique business objectives, target audience, and desired app functionalities. This collaborative approach enables us to design and develop mobile apps that align with our clients' vision and provide exceptional user experiences.</p>


          


        </div>

        <div className='bg-black text-white  w-1/2  items-start flex pt-16 pb-16' >


        <div className='wrapper'>

<div className=' parent'>

<div className=' child'>

  <img 
    src="/images/why-turntabl.png"
    alt='logo'
    width={400}
    height={400}
    className='object-contain'
  />
</div>


</div>

</div>  

          


        </div>
      </div>

      

        <div className='flex'>
          

          <div className='bg-black text-white  w-1/2  items-start flex pt-16 pb-16' >

            <div className='wrapper'>

            <div className=' parent'>

            <div className=' child pl-80'>

              <img 
                src="/images/why-turntabl.png"
                alt='logo'
                width={400}
                height={400}
                className='object-contain'
              />
            </div>
            

            </div>

            </div>            

          </div>


          <div className='bg-black text-white  w-1/2  items-start  pt-16 pb-16 pr-80' >
            

          


            <h1 className=' text-4xl text_green'> Web App Development </h1>
            <p>Our team of skilled web app developers possesses expertise in various technologies and frameworks, ensuring that we can deliver tailored solutions that meet our clients' unique requirements. We work closely with our clients to understand their specific business objectives, user needs, and desired functionalities. This collaborative approach allows us to design and develop web applications that align with our clients' vision and deliver exceptional user experiences.</p>
            

            


          </div>

        </div>
      
      
      
    </div>
  )
}

export default page