import Header from '@/components/Header'
import React from 'react'

export const metadata = {
  title: 'Our Services',
  description: 'Generated by create next app',
  icons:{
    icon: "/favicon.ico"
  }
}

type Props = {}

const page = (props: Props) => {
  return (
    <div className='min-h-[100vh]' >
      <Header 
      title='Our Services'
      description='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
      image='contact-header.jpg'
      />


      <div className='flex h-96'>

        <div className='bg-black w-3/5  items-start pl-96 pt-40 pb-16' >


          <h1 className=' text-4xl text-teal-300'> Leading global talent </h1>
          <h1 className=' text-4xl text-white'> to your software</h1>
          <h1 className=' text-4xl text-white'> solutions </h1>




        </div>

        <div className=' bg-black w-2/5  items-start flex' >


          <div className=' pt-36'>

            <img 
              src="/images/__Turntabl_Digital_Hand_5.png"
              alt='logo'
              width={200}
              height={200}
              className='object-contain'
            />

          </div>


        </div>
      </div>




      
      


      <div className='flex'>

        <div className='  w-1/2  items-start pl-80 pt-16 pb-16' >


          <h1 className=' text-4xl'> Software consultancy </h1>
          <p>We listen to your issues first.</p>
          <p>And after you get industry-leading services.</p>
          <p>from a professional solutions team.</p>

          


        </div>

        <div className='  w-1/2  items-start flex pt-16 pb-16' >


          <div className=''>

          <img 
            src="/images/why-turntabl.png"
            alt='logo'
            width={400}
            height={400}
            className='object-contain'
          />

          </div>

          


        </div>
      </div>

      <div className='flex'>

        <div className='  w-1/2  items-start flex pt-16 pb-16' >


          <div className=' pl-80'>

            <img 
              src="/images/why-turntabl.png"
              alt='logo'
              width={400}
              height={400}
              className='object-contain'
            />

          </div>

        </div>


        <div className='  w-1/2  items-start  pt-16 pb-16' >


          <h1 className=' text-4xl'> Software consultancy </h1>
          <p>We listen to your issues first.</p>
          <p>And after you get industry-leading services.</p>
          <p>from a professional solutions team.</p>

          


        </div>

      </div>

      <div className='flex'>

        <div className=' bg-black w-1/2  items-start pl-80 pt-16 pb-16' >


          <h1 className=' text-4xl text-white '> Software consultancy </h1>
          <p className=' text-white' >We listen to your issues first.</p>
          <p className=' text-white' >And after you get industry-leading services.</p>
          <p className=' text-white' >from a professional solutions team.</p>

          


        </div>

        <div className=' bg-black w-1/2  items-start flex pt-16 pb-16' >


          <div className=''>

          <img 
            src="/images/why-turntabl.png"
            alt='logo'
            width={400}
            height={400}
            className='object-contain'
          />

          </div>

          


        </div>
      </div>

      <div className='flex'>

        <div className=' bg-black w-1/2  items-start flex pt-16 pb-16' >


          <div className=' pl-80'>

            <img 
              src="/images/why-turntabl.png"
              alt='logo'
              width={400}
              height={400}
              className='object-contain'
            />

          </div>

        </div>


        <div className=' bg-black w-1/2  items-start  pt-16 pb-16' >


          <h1 className=' text-4xl text-white'> Software consultancy </h1>
          <p className=' text-white' >We listen to your issues first.</p>
          <p className=' text-white' >And after you get industry-leading services.</p>
          <p className=' text-white' >from a professional solutions team.</p>

          


        </div>

      </div>
      
      
    </div>
  )
}

export default page